import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/HeaderNav/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="text-foreground bg-linear-to-br from-[#b6ccda] to-[#c8dce5] px-8">
        <Header />
        {children}
      </body>
    </html>
  );
}
